[build]
  command = "npm install && npm --prefix apps/web install && npm --prefix apps/web run build"
  publish = "apps/web/.next"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev --prefix apps/web"
  targetPort = 3000
  port = 8888
  autoLaunch = true
