[build]
  command = "npm install && npm --prefix apps/web install && npm --prefix apps/web run build"
  publish = "apps/web/.next"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "netlify dev"
